_commit: 0.11.0
_src_path: ../templates/act-template-rust
component_ref: actpkg.dev/library/anydoc
description: Convert Word, PowerPoint, Excel, OpenDocument, RTF, EPUB, CSV and PDF
    documents to GitHub-Flavored Markdown
needs_filesystem: true
needs_http: false
project_name: anydoc
